---
title: "Untitled"
author: "Zachary M. Smith"
date: "2/13/2020"
output: html_document
---

# Relative Abundance (%) Metrics

Generally, abundance metrics are better represented on a normalized scale. Calculating the relative abundance (percentage) of a subset metrics should provide a more robust measure than raw abundance measures.
```{r rel_abund}
pct.df <- nest.df %>% 
  dplyr::mutate(
    pct_ephemeroptera = taxa_pct(.dataframe = .,
                                 .key_col = uid,
                                 .counts_col = total,
                                 .filter = order %in% "ephemeroptera",
                                 .unnest_col = data),
    pct_ept = taxa_pct(.dataframe = .,
                       .key_col = uid,
                       .counts_col = total,
                       .filter = order %in% c("ephemeroptera",
                                              "plecoptera",
                                              "trichoptera"),
                       .unnest_col = data),
    pct_shred = taxa_pct(.dataframe = .,
                         .key_col = uid,
                         .counts_col = total,
                         .filter = grepl("sh", ffg),
                         .unnest_col = data)
  )
```

```{r rel_abund_tbl, echo=FALSE}
standard_dt(pct.df)
```
