---
title: "Untitled"
author: "Zachary M. Smith"
date: "2/13/2020"
output: html_document
---

# Sequence Through Multiple Metrics

```{r seq_rich}
seq.df <- nest.df %>% 
  bind_cols(
    taxa_seq(.dataframe = .,
             .key_col = uid,
             .counts_col = total,
             .filter_cols_vec = c("class", "order"),
             .group_col = genus,
             .job = "rich",
             .unnest_col = data))
```


```{r seq_rich_tbl, echo=FALSE}
standard_dt(seq.df)
```


```{r seq_mult}
seq_mult.df <- nest.df %>% 
  bind_cols(
    taxa_seq(.dataframe = .,
             .key_col = uid,
             .counts_col = total,
             .filter_cols_vec = c("class", "order", "family"),
             .group_col = genus,
             .job = "rich",
             .unnest_col = data),
    taxa_seq(.dataframe = .,
             .key_col = uid,
             .counts_col = total,
             .filter_cols_vec = c("class", "order", "family"),
             .group_col = genus,
             .job = "pct",
             .unnest_col = data),
    taxa_seq(.dataframe = .,
             .key_col = uid,
             .counts_col = total,
             .filter_cols_vec = c("class", "order", "family"),
             .group_col = genus,
             .base_log = 2,
             .job = "shannon",
             .unnest_col = data))
```


```{r seq_mult_tbl, echo=FALSE}
standard_dt(seq_mult.df)
```
